<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-LJIGLQGO" failures="9" tests="29" name="My Test" time="152.018" errors="0" timestamp="07 Mar 2023 15:11:42 GMT">
  <testcase classname="testCases.LoginTestCases" name="verifyCheckBox" time="0.054"/>
  <testcase classname="testCases.LoginTestCases" name="verifyLoginForInValidUser" time="1.287">
    <failure type="java.lang.AssertionError" message="Alert same as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: Alert same as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
at testCases.LoginTestCases.verifyLoginForInValidUser(LoginTestCases.java:53)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginForInValidUser -->
  <testcase classname="testCases.LoginTestCases" name="verifyLoginForInValidUserwithExcelDataProvider" time="0.596">
    <failure type="java.lang.AssertionError" message="Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginForInValidUserwithExcelDataProvider -->
  <testcase classname="testCases.LoginTestCases" name="verifyLoginForInValidUserwithExcelDataProvider" time="0.642">
    <failure type="java.lang.AssertionError" message="Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginForInValidUserwithExcelDataProvider -->
  <testcase classname="testCases.LoginTestCases" name="verifyLoginForInValidUserwithExcelDataProvider" time="0.601">
    <failure type="java.lang.AssertionError" message="Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginForInValidUserwithExcelDataProvider -->
  <testcase classname="testCases.LoginTestCases" name="verifyLoginForInValidUserwithExcelDataProvider" time="0.618">
    <failure type="java.lang.AssertionError" message="Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: Alert not as expected expected [�
Alert!
Invalid Username/Password] but found [×
Alert!
Invalid Username/Password]
at testCases.LoginTestCases.verifyLoginForInValidUserwithExcelDataProvider(LoginTestCases.java:70)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginForInValidUserwithExcelDataProvider -->
  <testcase classname="testCases.LoginTestCases" name="verifySignInButtonColor" time="0.024"/>
  <testcase classname="testCases.LoginTestCases" name="verifySignInButtonText" time="0.024"/>
  <testcase classname="testCases.HomePageTestCases" name="verifyHomePageTitle" time="1.38"/>
  <testcase classname="testCases.HomePageTestCases" name="verifyHomePageURL" time="1.425"/>
  <testcase classname="testCases.HomePageTestCases" name="verifyUserLogout" time="2.048"/>
  <testcase classname="testCases.ExpenseCategoryTestCases" name="EditExpenseCategory" time="3.739">
    <failure type="java.lang.AssertionError" message="::Item not updated expected [�
Alert!
Category Updated Successfully] but found [×
Alert!
Category Updated Successfully]">
      <![CDATA[java.lang.AssertionError: ::Item not updated expected [�
Alert!
Category Updated Successfully] but found [×
Alert!
Category Updated Successfully]
at testCases.ExpenseCategoryTestCases.EditExpenseCategory(ExpenseCategoryTestCases.java:92)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- EditExpenseCategory -->
  <testcase classname="testCases.ExpenseCategoryTestCases" name="addNewExpenseCategory" time="3.607"/>
  <testcase classname="testCases.ExpenseCategoryTestCases" name="deleteExpenseCategory" time="3.182">
    <failure type="java.lang.IllegalArgumentException" message="Cannot find elements when the XPath is null.">
      <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
at org.openqa.selenium.internal.Require$ArgumentChecker.nonNull(Require.java:204)
at org.openqa.selenium.By$ByXPath.<init>(By.java:287)
at org.openqa.selenium.By.xpath(By.java:89)
at elementRepository.ExpenseCategory.deleteItem(ExpenseCategory.java:183)
at testCases.ExpenseCategoryTestCases.deleteExpenseCategory(ExpenseCategoryTestCases.java:69)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- deleteExpenseCategory -->
  <testcase classname="testCases.ExpenseCategoryTestCases" name="searchExpenseCategory" time="2.604">
    <failure type="java.lang.AssertionError" message="::Search is working expected [orange] but found [.........RESULT NOT FOUND.......]">
      <![CDATA[java.lang.AssertionError: ::Search is working expected [orange] but found [.........RESULT NOT FOUND.......]
at testCases.ExpenseCategoryTestCases.searchExpenseCategory(ExpenseCategoryTestCases.java:59)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- searchExpenseCategory -->
  <testcase classname="testCases.ExpenseCategoryTestCases" name="verifyExpenseCategoryPageIsLoaded" time="2.071"/>
  <testcase classname="testCases.ExpenseCategoryTestCases" name="verifyNewSearchResetButtonColors" time="2.03"/>
  <testcase classname="testCases.ManageExpensesTestCases" name="verifyAddExpenseFieldsPresence" time="4.312"/>
  <testcase classname="testCases.ManageExpensesTestCases" name="verifyAddNewExpenseRecord" time="7.058">
    <failure type="java.lang.AssertionError" message="::Expense record created expected [�
Alert!
Expense Record Created Successfully] but found [×
Alert!
Expense Record Created Successfully]">
      <![CDATA[java.lang.AssertionError: ::Expense record created expected [�
Alert!
Expense Record Created Successfully] but found [×
Alert!
Expense Record Created Successfully]
at testCases.ManageExpensesTestCases.verifyAddNewExpenseRecord(ManageExpensesTestCases.java:90)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddNewExpenseRecord -->
  <testcase classname="testCases.ManageExpensesTestCases" name="verifyManageExpensePageLoad" time="2.537"/>
  <testcase classname="testCases.ManageExpensesTestCases" name="verifyNewSearchResetButtonFontColor" time="2.916"/>
  <testcase classname="testCases.ManageExpensesTestCases" name="verifyNewSearchResetButtonFontSize" time="2.473"/>
  <testcase classname="testCases.ManageProductTestCases" name="verifyAddNewProductPageDefaultCheckboxValuesSelected" time="3.56"/>
  <testcase classname="testCases.ManageProductTestCases" name="verifyAddNewProductPageDefaultRadioButtonValues" time="3.593"/>
  <testcase classname="testCases.ManageProductTestCases" name="verifyManageProductPageisLoaded" time="3.53"/>
  <testcase classname="testCases.ManageProductTestCases" name="verifyManageProductTitle" time="2.072"/>
  <testcase classname="testCases.ManageProductTestCases" name="verifyManageProductURL" time="2.089"/>
  <testcase classname="testCases.ManageProductTestCases" name="verifyProductSearchPageLoad" time="2.136"/>
  <testcase classname="testCases.LoginTestCases" name="verifyLoginForValidUser" time="1.325"/>
</testsuite> <!-- My Test -->
